### ISSUE TITLE
Tab Strip orientation change issue.

### ISSUE THREAD

**Issue by Nidhee** [nrlnishan/ViewPager-Swift#1]
Hello, 
1. Initially view on portrait mode, and when view changes from portrait to landscape, it does not change the width likewise, it fixes the width of tab strip to what it was on portrait mode. 
2. Initially view on landscape mode, and when view changes from landscape to portrait, it does not squeeze width accordingly and some tab items remains hidden.

Please guide, me what should I do to have changes in width on dynamic screen orientation.
Thanks.

**Comment by nrlnishan** [comment]
Since the frame of the view of the **ViewPagerController** is setup at the beginning, the tab strip may be fixed on its previous value. Can you try updating the frame of the view of the **ViewPagerController** on orientation change for a time being? I will try to incorporate fix for this issue asap.

**Comment by Nidhee** [comment]
Okay. can u give me some hint on how to do it. I am newbie in ios swift.

**Comment by nrlnishan** [comment]
I have updated the code and incorporated the fix for orientation change. Please check the documentation once for changes (some minor changes).
