### ISSUE TITLE
Color Issues

### ISSUE THREAD

**Issue by eastswift** [nrlnishan/ViewPager-Swift#10]
Cool!! ViewPager!

**Comment by nrlnishan** [comment]
Hey @eastswift, Thanks.

Do you have any issue ? because i saw something mentioned regarding colors in my mail whereas found that you have edited that comment. Is your issue fixed ? 

If you are still facing issue, can you elaborate more on that?

**Comment by eastswift** [comment]
There are issues. The background color of the navigation bar and TABBAR does not change. Shadows come and go. What should I do?

**Comment by nrlnishan** [comment]
@eastswift , can you please explain more? I have tried changing background color for navigation bar and its changing correctly. Also what do you mean "Shadows come and go" ? Can you post relevant screenshots and code of what you are trying to achieve?

Still i will provide you with solutions regarding common scenario.

1. ViewPager tabs shows behind navigation bar 
`self.edgesForExtendedLayout = UIRectEdge.init(rawValue: 0)`. Write it in `viewDidLoad` method of your view controller where you setup ViewPager.

2. For changing color of navigation bar , use
`self.navigationController?.navigationBar.barTintColor = UIColor.blue`.  Use barTintColor instead of tintColor. This should change your navigation bar to blue color

**Comment by eastswift** [comment]
I'm sorry. It was my mistake. Your open source is Cool! Have a nice day :)

Thank you for your reply.
