### ISSUE TITLE
Black Screen showing on lunch

### ISSUE THREAD

**Issue by Ziyaaad** [nrlnishan/ViewPager-Swift#37]
![image uploaded from ios 3](https://user-images.githubusercontent.com/36990967/36899853-5b668166-1e3a-11e8-9576-5385864f8747.jpg)

Hello, I'm having an issue when launching the app (only happens when launching the app) , a black screen appears and you need to swipe to the next object for it to disappear and the pager to run normally. Can you help on how to fix the issue please?

**Comment by nrlnishan** [comment]
Hi @Ziyaaad , 

There doesn't seem to be any problem with the library.  Is there something that you are doing wrong on your side? Or can you post necessary codes or relevant links so that i can see what the problem is?

Also, Here is the link for example of using ViewPager. [ViewPager-Example](https://github.com/nrlnishan/ViewPager-Swift/blob/master/ViewPager-Swift/MainViewController.swift)

Thanks :)

**Comment by Ziyaaad** [comment]
![screen shot 2018-03-05 at 09 04 26](https://user-images.githubusercontent.com/36990967/36958586-690cf8fe-2056-11e8-8181-b229938ee475.png)

Thank you for the response. I'm using a tab bar controller and navigation controller which is connected to the view-pager. When I select "Modules" on my tab bar, a black screen is displayed as shown in my post above. I need to swipe the screen first then the pager works normally (only on launch). Can you help please?
