### ISSUE TITLE
Scroll Problem

### ISSUE THREAD

**Issue by vre142** [nrlnishan/ViewPager-Swift#6]
Hi,
Thank you for your quick response. I have one problem with this library when I swipe the screen from right to left view pager change but when the next page is out of the screen title list of pages doesn't scroll. how can I fix this?

Thanks,
Vafa

**Comment by nrlnishan** [comment]
Hi, 
Can you provide the steps for recreating this issue. Also i have pushed new code and didn't find any of the above mentioned issue. Please check it out once

Thanks

**Comment by nrlnishan** [comment]
Hi, i have pushed new code in master branch with swift 3 support. Please check it out . This issue is not present in current swift 3 code. I have checked for the issue in previous code and couldnot recreate it. Also the code has been updated in viewpager-swift2.2 branch for previous project. Thus closing this issue for now.

**Comment by nileshk-iprogrammer** [comment]
Hi,
How to change the image on current selected tab?

**Comment by yashinls** [comment]
Hi @nrlnishan, I have this same issue. This happens when "isTabIndicatorAvailable" is set to false and "isTabHighlightAvailable" is set to true. When "isTabIndicatorAvailable" is set to true, the tabContainer scrolls.

I found another issue. I shall report it as a new bug( #21 )

**Comment by yashinls** [comment]
Thanks for the quick update.
